### ISSUE TITLE
Server: API should explode crawler results into individual DB entries

### ISSUE THREAD

**Issue by wadealexc** [wadeAlexC/ipbw#5]
The crawler sends the server a mapping (ex: `id -> [ids]`). The server is really dumb right now and just kinda dumps that into the database like last week's potatoes.

To make this easier to manage, the server should:
* Expand the mapping into `[(id1, id2)]` so that all relations are explicit DB entries. 
* Slap indices on all those entries so we can manage each entry individually

**Comment by dmuhs** [comment]
Fixed in 72c5388
